spring:
  application:
    name: travel-management-ms
  data:
    mongodb:
      uri: ${MONGO_PUBLIC_URL}
      database: trips

server:
  servlet:
    context-path: /travel-management-ms
  port: 8080
  ssl:
    enabled: false
  management:
    endpoints.web.exposure.include: health, info
    endpoint:
      health:
        probes:
          enabled: true
    server:
      port: 8080
